Manual Docs 2
misteroneill/video.js pull request #1
Opened 2016-11-18 20:54 UTC by misteroneill

Moved the "removing players" guide to "player workflows" guide.

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [ ] Reviewed by Two Core Contributors

2016-11-28 18:52 UTC, brandonocasey requested changes

2016-11-28 18:52 UTC, BrandonOCasey commented on docs/guides/player-workflows.md
> +
Should this file contain other advanced workflows? like using `ready` or maybe using other events on the player to do things.

2016-11-29 19:51 UTC, gkatsev commented on docs/guides/player-workflows.md
> +
We should add a story to writeup a simple way of using videojs with React.

2016-11-29 19:51 UTC, gkatsev commented on docs/guides/player-workflows.md
> +### Signs of an Undisposed Player
This reminds me, we should add the `vdata123124` and this as a question in the FAQ.

2016-11-29 19:51 UTC, gkatsev commented on docs/guides/player-workflows.md
> +### Signs of an Undisposed Player
The vdata error is a similar thing where the element was removed from the DOM but an event triggered for it.

2016-11-29 19:51 UTC, gkatsev commented on docs/guides/player-workflows.md
> +
Looks like this was originally a "removing players" document.

2016-11-29 19:57 UTC, brandonocasey commented on docs/guides/player-workflows.md
> +
it might be a good idea to make an issue for this just in case

2016-11-30 21:47 UTC, misteroneill commented on docs/guides/player-workflows.md
> +
Yeah, this was the "removing players" document. I think it makes sense to have a document devoted to "doing things with players other than creating them". That's the intent of this.

2016-11-30 21:51 UTC, misteroneill commented on docs/guides/player-workflows.md
> +### Signs of an Undisposed Player
I'll mention both.

2016-11-30 21:54 UTC, misteroneill commented on docs/guides/player-workflows.md
> +
`ready` is covered in the setup guide, I believe.

2016-11-30 21:55 UTC, misteroneill commented on docs/guides/player-workflows.md
> +
And I added a section at the bottom for "Using Video.js with..." and empty sub-headings for jQuery, React, Ember, and Angular.

2016-12-01 20:47 UTC, BrandonOCasey commented on docs/guides/player-workflows.md
> +### Signs of an Undisposed Player
vdata was added to the troubleshooting/faq guides

2016-12-01 20:48 UTC, brandonocasey approved these changes

2016-12-02 15:16 UTC, closed without merging